version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" # Проброс порта
    command: ["redis-server", "--appendonly", "yes"] # Включение персистентности
    volumes:
      - redis_data:/data # Хранение данных на хосте
    restart: unless-stopped

volumes:
  redis_data: